/**
 * Design system runtime config.
 *
 * The available axes, their values, and the defaults are declared once in
 * `dssoca.config.ts`; this module derives its types + defaults from that
 * manifest and provides the runtime helpers (see DESIGN.md):
 *   • color — written as [data-theme]
 *   • size  — written as [data-size-variant]  (renamed from `density` in 0.4.0)
 *
 * Sizing has three layers (highest priority first):
 *   1. a component's `size` prop          (per instance)
 *   2. `componentsSize[Name]`             (per-component default)
 *   3. `sizeVariant` on an ancestor       (global default; `md` out of the box)
 */

import {
  dssocaConfig,
  PALETTE_SLOTS,
  type ColorTheme,
  type Size,
  type ComponentName,
  type ComponentsSize,
  type SpinnerVariant,
  type Palette,
  type ThemePalette,
  type PaletteSlot,
} from './dssoca.config.js'

// Re-exported so the `dssoca` / `./config` import paths expose the config vocab.
export { dssocaConfig, PALETTE_SLOTS }
export type { ColorTheme, Size, ComponentName, ComponentsSize, SpinnerVariant }
export type { Palette, ThemePalette, PaletteSlot }
export type { DssocaConfig, DesignAxis } from './dssoca.config.js'

export interface DesignConfig {
  theme: ColorTheme
  /** Global default size for every component — written as [data-size-variant]. */
  sizeVariant: Size
  /** Per-component default sizes; components not listed inherit `sizeVariant`. */
  componentsSize: ComponentsSize
  /**
   * Global default Spinner glyph (DS-0108). Unlike `theme`/`sizeVariant` this is
   * NOT a CSS axis — it is never painted as a `data-*` attribute (see
   * `designAttributes`, which intentionally omits it). It threads to the Spinner
   * component through `resolveSpinnerVariant`; a per-usage `variant` prop wins.
   */
  spinnerVariant: SpinnerVariant
  /**
   * Custom root palette (color rework) — both themes' 19 slot values, e.g.
   * generated by the docs Theme Builder. `null` = the built-in palette.
   * Tri-state in `applyDesignConfig` partials: omit to keep the current
   * palette, pass a `Palette` to set one, pass `null` to clear back to the
   * stylesheet values. Applied as inline custom properties for the ACTIVE
   * theme only, and re-written on every call so a theme flip never gets
   * masked by stale inline values.
   */
  palette: Palette | null
}

/** Defaults derived from the manifest — change them in `dssoca.config.ts`. */
export const defaultDesignConfig: DesignConfig = {
  theme: dssocaConfig.theme.default,
  sizeVariant: dssocaConfig.size.default,
  componentsSize: {},
  spinnerVariant: dssocaConfig.spinner.default,
  palette: null,
}

let current: DesignConfig = {
  ...defaultDesignConfig,
  componentsSize: { ...defaultDesignConfig.componentsSize },
}

const copyPalette = (p: Palette | null): Palette | null =>
  p === null ? null : { dark: { ...p.dark }, light: { ...p.light } }

/** camelCase slot → its CSS custom property ('brightBlack' → '--ss-bright-black'). */
export const paletteSlotVar = (slot: PaletteSlot): string =>
  '--ss-' + slot.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase())

/** Current resolved config (last applied, or defaults). */
export function getDesignConfig(): DesignConfig {
  return {
    ...current,
    componentsSize: { ...current.componentsSize },
    palette: copyPalette(current.palette),
  }
}

/**
 * Build the `data-*` attribute map for a config — handy for SSR / markup so the
 * correct theme + size paint on the first frame with no flash.
 *
 *   <html {...designAttributes({ sizeVariant: 'sm' })}> … </html>
 *
 * Only the CSS axes (`theme`, `sizeVariant`) appear here. `spinnerVariant` is a
 * default-prop axis, not a CSS one, so it is deliberately omitted (DS-0108) — it
 * is consumed via `resolveSpinnerVariant`, never as a `data-*` attribute.
 */
export function designAttributes(config: Partial<DesignConfig> = {}): {
  'data-theme': ColorTheme
  'data-size-variant': Size
} {
  const merged = { ...defaultDesignConfig, ...config }
  return { 'data-theme': merged.theme, 'data-size-variant': merged.sizeVariant }
}

/**
 * Apply theme + size to a DOM element (defaults to <html>). Merges over the
 * current config so callers can flip one axis at a time (`componentsSize` is
 * merged key-by-key). SSR-safe: no-op when no document and no explicit target.
 */
export function applyDesignConfig(
  config: Partial<DesignConfig> = {},
  target?: HTMLElement,
): DesignConfig {
  current = {
    ...current,
    ...config,
    componentsSize: { ...current.componentsSize, ...(config.componentsSize ?? {}) },
    // Tri-state: absent = keep, Palette = set (defensive copy), null = clear.
    palette: config.palette === undefined ? current.palette : copyPalette(config.palette),
  }
  const el = target ?? (typeof document !== 'undefined' ? document.documentElement : undefined)
  if (el) {
    el.setAttribute('data-theme', current.theme)
    el.setAttribute('data-size-variant', current.sizeVariant)
    // Palette runs on EVERY call: inline slot values always track the active
    // theme (a later theme flip re-writes the other set), and clearing removes
    // them so the stylesheet palette resumes.
    for (const slot of PALETTE_SLOTS) {
      if (current.palette)
        el.style.setProperty(paletteSlotVar(slot), current.palette[current.theme][slot])
      else el.style.removeProperty(paletteSlotVar(slot))
    }
  }
  return getDesignConfig()
}

/**
 * Emit a custom palette as a CSS override block — the zero-JS / SSR path. Ship
 * it AFTER `dssoca/theme.css` in source order (equal specificity, order wins):
 *
 *   <style>{paletteToCss(palette)}</style>
 *
 * The docs Theme Builder's "CSS" export is exactly this output.
 */
export function paletteToCss(palette: Palette): string {
  const block = (selector: string, theme: ThemePalette) =>
    `${selector} {\n${PALETTE_SLOTS.map((s) => `  ${paletteSlotVar(s)}: ${theme[s]};`).join('\n')}\n}`
  return [
    block(`:root,\n[data-theme='dark']`, palette.dark),
    block(`[data-theme='light']`, palette.light),
  ].join('\n\n')
}

/**
 * Resolve the size a component should APPLY on its own root (as
 * `data-size-variant`), or `undefined` to inherit the global `sizeVariant`
 * through the cascade. Resolution order: explicit `size` prop →
 * `componentsSize[name]` → inherit.
 */
export function resolveComponentSize(name: ComponentName, size?: Size): Size | undefined {
  return size ?? current.componentsSize[name]
}

/**
 * Resolve the Spinner glyph a component should render: an explicit `variant`
 * wins, else the configured global `spinnerVariant` (DS-0108). Mirrors
 * `resolveComponentSize`, but ALWAYS returns a concrete variant (never
 * `undefined`) — there is no CSS cascade for the glyph, so the component needs a
 * definite value to pick frames.
 */
export function resolveSpinnerVariant(variant?: SpinnerVariant): SpinnerVariant {
  return variant ?? current.spinnerVariant
}
