/**
 * dssoca configuration manifest — the single source of truth for *how the
 * design system is configured*: which axes exist, the values each one allows,
 * and the system defaults. `config.ts` derives its types and defaults from
 * here, so adding a value (or a whole new axis) is a one-place change.
 *
 * Two axes today (see DESIGN.md):
 *   • theme — color, written as [data-theme]
 *   • size  — chrome scale (sm | md | lg), written as [data-size-variant]
 *
 * The `size` axis replaced the former `density` axis in 0.4.0 (DS-0012):
 * compact → `sm`, comfy → `md`, plus a new `lg`. The global default is set by
 * `sizeVariant`; per-component defaults by `componentsSize`; per instance by a
 * component's `size` prop.
 */

/** One configurable axis: its allowed values + the default applied when unset. */
export interface DesignAxis<Values extends readonly string[] = readonly string[]> {
  /** Allowed values for the axis (by convention the default appears here too). */
  readonly values: Values
  /** The value applied when a consumer sets nothing. */
  readonly default: Values[number]
}

/**
 * Shape of the manifest — one entry per axis the design system understands.
 *
 * Note the asymmetry: `theme` and `size` are *CSS axes* (painted as
 * `data-theme` / `data-size-variant`); `spinner` is a plain default-prop axis
 * (the chosen Spinner glyph) with no `data-*` attribute — it threads through the
 * config to `resolveSpinnerVariant`, not the cascade (DS-0108).
 */
export interface DssocaConfig {
  readonly theme: DesignAxis
  readonly size: DesignAxis
  readonly spinner: DesignAxis
}

/**
 * Single source of truth for the Spinner *variant names* (DS-0108). The frame
 * data lives in `Spinner.svelte`'s `SPINNER_VARIANTS`, but its keys are pinned
 * to this list (`satisfies Record<SpinnerVariant, …>`) so the two cannot drift.
 */
export const SPINNER_VARIANT_NAMES = [
  'boxBounce2',
  'boxBounce',
  'squareCorners',
  'toggle2',
  'toggle3',
  'toggle4',
  'pipe',
  'line',
  'growVertical',
  'growHorizontal',
] as const

/** Spinner variant names — derived from the manifest's `spinner` axis. */
export type SpinnerVariant = (typeof dssocaConfig)['spinner']['values'][number]

/**
 * The manifest. `as const` preserves the value/default literals so the unions
 * below can be derived from it; `satisfies` validates the shape without widening.
 */
export const dssocaConfig = {
  theme: { values: ['dark', 'light'], default: 'dark' },
  size: { values: ['sm', 'md', 'lg'], default: 'md' },
  spinner: { values: SPINNER_VARIANT_NAMES, default: 'boxBounce2' },
} as const satisfies DssocaConfig

/** Color axis values — derived from the manifest (`'dark' | 'light'`). */
export type ColorTheme = (typeof dssocaConfig)['theme']['values'][number]

/**
 * The 19 root palette slots (color rework): the 16 ANSI terminal colors plus
 * `bg`, `fg`, and the one vivid `accent`. Every semantic `--ss-*` token derives
 * from these, so overriding them — via `applyDesignConfig({ palette })` or a
 * CSS block from `paletteToCss` — recolors the whole system. camelCase here;
 * the CSS custom property is the kebab-cased `--ss-` name
 * (`brightBlack` → `--ss-bright-black`).
 */
export const PALETTE_SLOTS = [
  'bg',
  'fg',
  'accent',
  'black',
  'red',
  'green',
  'yellow',
  'blue',
  'magenta',
  'cyan',
  'white',
  'brightBlack',
  'brightRed',
  'brightGreen',
  'brightYellow',
  'brightBlue',
  'brightMagenta',
  'brightCyan',
  'brightWhite',
] as const

export type PaletteSlot = (typeof PALETTE_SLOTS)[number]

/** One theme's palette — any CSS `<color>` string per slot (hex, oklch(), …). */
export type ThemePalette = Record<PaletteSlot, string>

/** A full custom palette: both themes, e.g. generated by the docs Theme Builder. */
export interface Palette {
  dark: ThemePalette
  light: ThemePalette
}

/** Size axis values — derived from the manifest (`'sm' | 'md' | 'lg'`). */
export type Size = (typeof dssocaConfig)['size']['values'][number]

/** Names of the components that accept a `size` prop / `componentsSize` entry. */
export const COMPONENT_NAMES = [
  'Accordion',
  'Avatar',
  'Badge',
  'BottomNav',
  'Button',
  'Card',
  'Chart',
  'Container',
  'DateField',
  'EmptyState',
  'FileDrop',
  'Heading',
  'Icon',
  'Image',
  'Input',
  'Kbd',
  'Link',
  'LogStream',
  'Menu',
  'MetricTile',
  'Modal',
  'NumberField',
  'Pagination',
  'SearchPalette',
  'SegmentedControl',
  'Select',
  'ServiceCard',
  'Sidebar',
  'Sparkline',
  'Spinner',
  'Switch',
  'Table',
  'Textarea',
  'Toaster',
  'Tooltip',
  'Topbar',
] as const

export type ComponentName = (typeof COMPONENT_NAMES)[number]

/** Per-component default sizes; any omitted component inherits `sizeVariant`. */
export type ComponentsSize = Partial<Record<ComponentName, Size>>
