/**
 * Theme Builder — export formats.
 *
 * A small registry so new targets are additive: v1 ships the two dssoca-native
 * formats (a runtime `applyDesignConfig` snippet and the `paletteToCss` CSS
 * override block). Terminal emulator formats — Windows Terminal / Alacritty /
 * Kitty / Xresources — are a planned follow-up: each lands as one more
 * `EXPORT_FORMATS` entry, nothing else changes.
 */

import { SLOTS, SLOT_TO_CSS_VAR, type Palette, type ThemePalette } from './types'

export interface ExportFormat {
  id: string
  label: string
  /** Prism language id for the docs CodeBlock. */
  lang: string
  generate(palette: Palette, meta: { accent: string; tint: number }): string
}

const pct = (tint: number) => `${Math.round(tint * 100)}%`

const tsTheme = (theme: ThemePalette) =>
  SLOTS.map((slot) => `    ${slot}: '${theme[slot]}',`).join('\n')

/** The exact `paletteToCss` block shape (dssoca/src/lib/config.ts). */
const cssBlock = (selector: string, theme: ThemePalette) =>
  `${selector} {\n${SLOTS.map((slot) => `  ${SLOT_TO_CSS_VAR[slot]}: ${theme[slot]};`).join('\n')}\n}`

export const EXPORT_FORMATS: ExportFormat[] = [
  {
    id: 'ts',
    label: 'TypeScript',
    lang: 'ts',
    generate: (palette, meta) =>
      [
        `import { applyDesignConfig, type Palette } from 'dssoca'`,
        '',
        `// Generated by the dssoca Theme Builder — accent ${meta.accent}, tint ${pct(meta.tint)}`,
        'const palette: Palette = {',
        '  dark: {',
        tsTheme(palette.dark),
        '  },',
        '  light: {',
        tsTheme(palette.light),
        '  },',
        '}',
        '',
        'applyDesignConfig({ palette })',
        '',
      ].join('\n'),
  },
  {
    id: 'css',
    label: 'CSS',
    lang: 'css',
    generate: (palette, meta) =>
      [
        `/* dssoca palette override — Theme Builder (accent ${meta.accent}, tint ${pct(meta.tint)}) — load AFTER dssoca/theme.css */`,
        cssBlock(`:root,\n[data-theme='dark']`, palette.dark),
        '',
        cssBlock(`[data-theme='light']`, palette.light),
        '',
      ].join('\n'),
  },
]
